### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by janezlapajne** [conor-horgan/spectrai#2]
Hello,

I am writing to you about the licence permits. I want to use part of the code for my research. What kind of legal obligations will I have to abide by? I will make it available to the public and also cite your work. Thanks!

**Comment by conor-horgan** [comment]
Hi, spectrai is licensed under an Apache-2.0 license (https://github.com/conor-horgan/spectrai/blob/main/LICENSE). You are completely free to use it for your research (I hope it’s helpful!), though a citation would always be appreciated 😊

**Comment by janezlapajne** [comment]
Thank you! Just wanted to make sure. Anyways, great work, it helped me a lot!
